"""empty message

Revision ID: 0289fe0309e6
Revises: 6bedd65c3fe3
Create Date: 2024-10-30 00:03:34.560317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0289fe0309e6'
down_revision = '6bedd65c3fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        # batch_op.drop_constraint('instagram_profile_id', type_='foreignkey')
        batch_op.create_foreign_key('owner_id', 'instagram_page', ['owner_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_profile_pic_url', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('instagram_page_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('instagram_page_id', 'instagram_page', ['instagram_page_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('instagram_page_id', type_='foreignkey')
        batch_op.drop_column('instagram_page_id')
        batch_op.drop_column('saved_profile_pic_url')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('owner_id', type_='foreignkey')
        batch_op.create_foreign_key('instagram_profile_id', 'instagram_profile', ['owner_id'], ['id'])

    # ### end Alembic commands ###
