"""empty message

Revision ID: 0e2c93994d1b
Revises: 4375faf970fd
Create Date: 2024-10-28 02:58:34.293803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2c93994d1b'
down_revision = '4375faf970fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instagram_page', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instagram_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
