"""empty message

Revision ID: 4375faf970fd
Revises: f7399d60a2ad
Create Date: 2024-10-28 02:42:27.997259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4375faf970fd'
down_revision = 'f7399d60a2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instagram_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follows_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instagram_page', schema=None) as batch_op:
        batch_op.drop_column('follows_count')
        batch_op.drop_column('followers_count')

    # ### end Alembic commands ###
