"""empty message

Revision ID: 6bedd65c3fe3
Revises: c6669a9b9f47
Create Date: 2024-10-29 16:03:02.770106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bedd65c3fe3'
down_revision = 'c6669a9b9f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        # batch_op.drop_constraint('instagram_profile_id', type_='foreignkey')
        batch_op.create_foreign_key('owner_id', 'instagram_page', ['owner_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_profile_pic_url', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('instagram_page_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('instagram_page_id', 'instagram_page', ['instagram_page_id'], ['id'])

    # ### end Alembic commands ###