"""empty message

Revision ID: a813ccf1573c
Revises: 62591283c4ae
Create Date: 2024-10-30 00:55:20.834623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a813ccf1573c'
down_revision = '62591283c4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('comment', schema=None) as batch_op:
    #     # batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('instagram_page', schema=None) as batch_op:
        batch_op.alter_column('searched_hashtags',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instagram_page', schema=None) as batch_op:
        batch_op.alter_column('searched_hashtags',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'instagram_profile', ['owner_id'], ['id'])

    # ### end Alembic commands ###
