"""empty message

Revision ID: cc03ce17ecd7
Revises: a813ccf1573c
Create Date: 2024-10-30 03:41:33.013264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc03ce17ecd7'
down_revision = 'a813ccf1573c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('comment', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=True))
        batch_op.drop_column('instagram_id')
        batch_op.drop_column('instagram_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_username', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('instagram_id', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('category')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'instagram_profile', ['owner_id'], ['id'])

    # ### end Alembic commands ###
