"""empty message

Revision ID: e956052b4dc8
Revises: cc03ce17ecd7
Create Date: 2024-10-30 12:49:19.206754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e956052b4dc8'
down_revision = 'cc03ce17ecd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('comment', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # with op.batch_alter_table('comment', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'instagram_profile', ['owner_id'], ['id'])

    # ### end Alembic commands ###
