"""empty message

Revision ID: f7399d60a2ad
Revises: 786272bbefe2
Create Date: 2024-10-28 02:25:45.803063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7399d60a2ad'
down_revision = '786272bbefe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instagram_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('searched_hashtags', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instagram_page', schema=None) as batch_op:
        batch_op.drop_column('searched_hashtags')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
